title: <p align="center"> Adisak Dadjam </p>

logo: "assets/IMG_5333.png"

description: |
  <p align="center">
    <a href="/pdf/resume.pdf">Resume</a> |
    <a href="https://www.linkedin.com/in/adisak-dadjam-05a283405/">LinkedIn</a> |
    <a href="https://github.com/AdisakDadjam">GitHub</a>
  </p>

  <p align="justify">
    I am a recent Statistics graduate from the Faculty of Science with experience in applying statistical methods for data analysis and hypothesis testing. I am passionate about building a career in Data Science, particularly in the medical field, where I can apply analytical skills to solve complex problems while continuing to learn and grow professionally.
  </p>

  <p align="justify">
    Email: OmeDadjam2547@gmail.com
  </p>

theme: jekyll-theme-minimal
