title: Adisak Dadjam
logo: "/assets/49635_ok.jpg"
description: >
  <p align="center">
    <a href="/pdf/resume.pdf">Resume</a> | 
    <a href="https://www.linkedin.com/in/adisak-dadjam-05a283405/">LinkedIn</a> | 
    <a href="https://github.com/AdisakDadjam">GitHub</a>
  </p>

  I am a Statistics graduate from the Faculty of Science with experience in applying statistical methods for data analysis and hypothesis testing. I am passionate about building a career in Data Science, particularly in the medical field, where I can apply analytical skills to solve complex problems while continuing to learn and grow professionally.

  **Email:** OmeDadjam2547@gmail.com
theme: jekyll-theme-minimal
